# kubectl label nodes <your-node-name> kubeadm=enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: kubeadm-oci
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: oci
      scope: kubeadm
  strategy: {}
  template:
    metadata:
      name: kubeadm-oci
      labels:
        provider: oci
        scope: kubeadm
    spec:
      restartPolicy: Always
      containers:
        - name: kubeadm-oci
          image: garutilorenzo/kubeadm:oci
          volumeMounts:
            - name: kubernetes-vol
              mountPath: /etc/kubernetes
      nodeSelector:
        kubeadm: enabled
      volumes:
        - name: kubernetes-vol
          hostPath:
            # directory location on host
            path: /etc/kubernetes
            # this field is optional
            type: Directory