FROM garutilorenzo/kubeadm:base
# trigger GitHub Actions CI
COPY kubeadm/docker-entrypoint-oci.sh /usr/local/bin/docker-entrypoint.sh
RUN ln -s usr/local/bin/docker-entrypoint.sh /entrypoint.sh # backwards compat
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["kubeadm"]