name: CI build kubeadm base aws image

on:
  push:
    branches:
    - master
    paths:
    - 'kubeadm/Dockerfile.base.aws'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build kubeadm main image
      uses: docker/build-push-action@v4
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./kubeadm/Dockerfile.base.aws
        platforms: linux/amd64,linux/arm64
        push: true
        tags: garutilorenzo/kubeadm:baseaws